In [ ]:
#1.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]

rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)


In [5]:
#ans-Explanation: Not enough samples for recursive elimination.
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
y = [1, 0, 1, 0, 1]
rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
print(X_new)


[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [ ]:
#2.
from sklearn.feature_selection import VarianceThreshold

X = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)


In [7]:
#ans-All features have zero variance.
from sklearn.feature_selection import VarianceThreshold
X = [[0, 1, 0], [0, 2, 1], [1, 1, 0]]
selector = VarianceThreshold(threshold=0.1)
X_new = selector.fit_transform(X)
print(X_new)


[[0 1 0]
 [0 2 1]
 [1 1 0]]


In [ ]:
#3.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 0, 0]]
similarity = cosine_similarity(data)


In [8]:
#ans-issue-Cosine similarity is undefined for zero vectors.
from sklearn.metrics.pairwise import cosine_similarity
data = [[5, 0, 3], [0, 1, 2]]
similarity = cosine_similarity(data)
print(similarity)


[[1.         0.46017899]
 [0.46017899 1.        ]]


In [ ]:
#4.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)


In [10]:
#ans-Not enough data, importance ranking is unstable.
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6], [7, 8], [2, 3]]
y = [1, 0, 1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
print(X_new)


[[1]
 [3]
 [5]
 [7]
 [2]]


In [ ]:
#5.
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rate': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating')


In [12]:
#ans- Explanation: Wrong column name rating.
import pandas as pd
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rating': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating')
print(pivot)


item   I1   I2
user          
A     5.0  3.0
B     NaN  4.0


In [ ]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=3)
X_new = pca.fit_transform(X)


In [13]:
#ans-Explanation: n_components > min(n_samples, n_features).
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=1)
X_new = pca.fit_transform(X)
print(X_new)


[[-3.67695526]
 [-0.84852814]
 [ 1.97989899]
 [ 4.80832611]
 [-2.2627417 ]]


In [ ]:
#7.
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
sim = cosine_similarity(ratings.T)


In [14]:
#ans-Explanation: NaNs must be handled first.ratings = ratings.fillna(0)
ratings = pd.DataFrame({
    'User1': [5, None, 3],
    'User2': [None, 4, None],
    'User3': [1, 2, None]
})
ratings = ratings.fillna(0)
sim = cosine_similarity(ratings.T)
print(sim)


[[1.         0.         0.38348249]
 [0.         1.         0.89442719]
 [0.38348249 0.89442719 1.        ]]


In [ ]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


In [15]:
user_vec = np.array([[1, 2]])
item_vec = np.array([[0.5], [1.0]])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: [[2.5]]


In [ ]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


In [16]:

#10.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors(metric='hamming')
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print("Neighbors (indices):", indices)


Neighbors (indices): [[0 2]]


In [ ]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([1, 0, 1])
b = np.array([0, 1, 1])

sim = cosine_similarity(a, b)
print("Similarity:", sim)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
a = np.array([1, 0, 1]).reshape(1, -1)
b = np.array([0, 1, 1]).reshape(1, -1)

sim = cosine_similarity(a, b)
print("Similarity:", sim)


Similarity: [[0.5]]
